from typing import Literal, TypedDict

import sgg._typing as sgt


class Dict_Font(TypedDict):
    fg: sgt.ColorTypeN = ...
    family: str = ...
    font_size: int | float = 14
    weight: Literal["normal", "bold"] = ...
    slant: Literal["roman", "italic"] = ...
    underline: bool = ...
    overstrike: bool = ...


class Dict_Input(Dict_Font):
    selectbackground: sgt.ColorTypeN = ...
    selectborderwidth: int | float = ...
    selectforeground: sgt.ColorTypeN = ...
    insertbg: str = ...
    insertborderwidth: float | str = 0
    insertofftime: int = 300
    insertontime: int = 600
    insertwidth: float | str = ...
    key: str | None = ...
