"""フレームワーク全体で使用する型を設定しているモジュール"""

from typing import Any, Literal

from numpy._typing import _NestedSequence
from numpy.random import Generator, SeedSequence

from ._array_date_unit import *
from ._array_dtype import *
from ._arraylike import *
from ._kwarg._graph import *
from ._kwarg._popup import *
from ._kwarg._widget import *
from ._scalar import *
from ._timezone import *
from ._widget import *

__all__ = [
    "_AnyShape",
    "_ArrayDT64",
    "_ArrayLikeBool_co",
    "_ArrayLikeBytes_co",
    "_ArrayLikeComplex_co",
    "_ArrayLikeDT64_co",
    "_ArrayLikeFloat_co",
    "_ArrayLikeInt_co",
    "_ArrayLikeNone_co",
    "_ArrayLikeNumber_co",
    "_ArrayLikeRealNumeric_co",
    "_ArrayLikeStr_co",
    "_ArrayLikeString_co",
    "_ArrayLikeStringDtype_co",
    "_ArrayLikeStrings_co",
    "_ArrayLikeTD64",
    "_ArrayLikeTD64_co",
    "_ArrayLikeTD64s_co",
    "_BoolDTypeLike",
    "_BoolScalar",
    "_ComparisonDT64",
    "_ComplexDtypeLike",
    "_ComplexScalar",
    "_DateWord_NAT",
    "_DateWord_NOW",
    "_DateWord_TODAY",
    "_DateWordAll",
    "_DateWordScalar",
    "_DT64Code",
    "_DT64Code_All",
    "_DT64Date",
    "_DT64Date_co",
    "_DT64Now",
    "_DT64Now_co",
    "_DT64Scalar",
    "_DTypeLike",
    "_DtypeLikeDT",
    "_DTypeLikeF32",
    "_DTypeLikeF64",
    "_DTypeLikeFloat",
    "_DTypeLikeInt",
    "_DTypeLikeInts",
    "_DtypeLikeTD",
    "_DTypeLikeUInt",
    "_DualArrayLike",
    "_FloatScalar",
    "_IntScalar",
    "_USE_IMG_TYPE",
    "_NaTValue",
    "_NaTValue_co",
    "_NestedSequence",
    "_NumberScalar",
    "_NumericDTypeLike",
    "_orderKACF",
    "_PatternBytesScalar",
    "_PatternStrScalar",
    "_RealNumeric_co",
    "_RealNumericDTypeLike",
    "_Seed",
    "_Shape",
    "_ShapeInt",
    "_ShapeLike",
    "_StringScalar",
    "_StringsDTypeLike",
    "_TD64Code",
    "_TD64Code_All",
    "_TD64Scalar",
    "_TimeByteUnit",
    "_TimeStrUnit",
    "_TimeUnit",
    "_TimezoneLiteral",
    "_TypeTimezone",
    "ColorListType",
    "ColorType",
    "ColorTypeN",
    "Dict_G_2DGraph",
    "Dict_G_3DGraph",
    "Dict_G_LinefillGraph",
    "Dict_G_Polar",
    "Dict_G_Radar",
    "Dict_Input",
    "Dict_P_Error",
    "Dict_P_Information",
    "Dict_P_Question",
    "Dict_P_Warning",
    "DTypeNLike",
    "GetList",
    "Incomplete",
    "NDArray",
    "NDBool",
    "NDBool_",
    "NDBools",
    "NDBytes_",
    "NDCharacter",
    "NDDatetime64",
    "NDFloating",
    "NDInteger",
    "NDNumber",
    "NDStr_",
    "NDString",
    "NDStringDtype",
    "NDTimedelta64",
    "NestedList",
    "RAny",
    "RBool",
    "RBool_",
    "RBools",
    "RBytes_",
    "RCharacter",
    "RComplex",
    "RComplex128",
    "RComplex64",
    "RDatetime64",
    "RFloat16",
    "RFloat64",
    "RInt64",
    "RInt8",
    "RNumber",
    "RObject",
    "RStr",
    "RStr_",
    "RString",
    "RTimedelta64",
    "RUInt64",
    "RUInt8",
    "RVoid",
    "Type_bool",
    "Type_Marker",
    "Type_Solid",
    "TypeArray2LikeNS",
    "TypeArray2LikeNumber",
    "TypeArray2LikeString",
    "TypeArrayLikeNS",
    "TypeArrayLikeNumber",
    "TypeArrayLikeString",
    "TypeArraysLikeNS",
    "TypeArraysLikeNumber",
    "TypeArraysLikeString",
    "Typeaxis",
    "Typetuple_float64",
]
type Type_bool = bool | Literal[0, 1, True, False]
type Incomplete = Any
type _Seed = int | SeedSequence | Generator | None
"""乱数のシード値"""
type _orderKACF = Literal["K", "A", "C", "F"] | None
type _USE_IMG_TYPE = Literal[
    "AVIF",
    "BLP",
    "BMP",
    "DDS",
    "DIB",
    "EPS",
    "GIF",
    "ICNS",
    "ICO",
    "IM",
    "JPEG",
    "JPEG 2000",
    "MPO",
    "MSP",
    "PCX",
    "PNG",
    "PPM",
    "QOI",
    "SGI",
    "SPIDER",
    "TGA",
    "TIFF",
    "WebP",
    "XBM",
]
"""読み込める画像ファイルの拡張子"""
