from typing import Literal

__all__ = [
    "_DT64Code",
    "_DT64Code_All",
    "_DT64Date",
    "_DT64Now",
    "_NaTValue",
    "_TD64Code",
    "_TD64Code_All",
    "_TimeByteUnit",
    "_TimeStrUnit",
    "_TimeUnit",
]
type _DT64Date = Literal["TODAY", "today", b"TODAY", b"today"]
type _DT64Now = Literal["NOW", "now", b"NOW", b"now"]
type _NaTValue = Literal["NAT", "NaT", "nat", b"NAT", b"NaT", b"nat"]
type _TimeStrUnit = Literal[
    "as",
    "D",
    "fs",
    "h",
    "m",
    "M",
    "ms",
    "ns",
    "ps",
    "s",
    "us",
    "W",
    "Y",
    "μs",
]
type _TimeByteUnit = Literal[
    b"as",
    b"D",
    b"fs",
    b"h",
    b"m",
    b"M",
    b"ms",
    b"ns",
    b"ps",
    b"s",
    b"us",
    b"W",
    b"Y",
]
type _TimeUnit = Literal[_TimeStrUnit, _TimeByteUnit]
type _DT64Code = Literal[
    "datetime64[as]",
    "datetime64[D]",
    "datetime64[fs]",
    "datetime64[h]",
    "datetime64[m]",
    "datetime64[M]",
    "datetime64[ms]",
    "datetime64[ns]",
    "datetime64[ps]",
    "datetime64[s]",
    "datetime64[us]",
    "datetime64[W]",
    "datetime64[Y]",
    "datetime64[μs]",
    "M8[as]",
    "M8[D]",
    "M8[fs]",
    "M8[h]",
    "M8[m]",
    "M8[M]",
    "M8[ms]",
    "M8[ns]",
    "M8[ps]",
    "M8[s]",
    "M8[us]",
    "M8[W]",
    "M8[Y]",
    "M8[μs]",
]
type _DT64Code_All = Literal[_DT64Code, _TimeUnit]
type _TD64Code = Literal[
    "timedelta64[as]",
    "timedelta64[D]",
    "timedelta64[fs]",
    "timedelta64[h]",
    "timedelta64[m]",
    "timedelta64[M]",
    "timedelta64[ms]",
    "timedelta64[ns]",
    "timedelta64[ps]",
    "timedelta64[s]",
    "timedelta64[us]",
    "timedelta64[W]",
    "timedelta64[Y]",
    "timedelta64[μs]",
    "m8[as]",
    "m8[D]",
    "m8[fs]",
    "m8[h]",
    "m8[m]",
    "m8[M]",
    "m8[ms]",
    "m8[ns]",
    "m8[ps]",
    "m8[s]",
    "m8[us]",
    "m8[W]",
    "m8[Y]",
    "m8[μs]",
]
type _TD64Code_All = Literal[_TD64Code, _TimeUnit]
