# ウィジェット
CURSOR_LIST = (
    "arrow",
    "man",
    "based_arrow_down",
    "middlebutton",
    "based_arrow_up",
    "mouse",
    "boat",
    "pencil",
    "bogosity",
    "pirate",
    "bottom_left_corner",
    "plus",
    "bottom_right_corner",
    "question_arrow",
    "bottom_side",
    "right_ptr",
    "bottom_tee",
    "right_side",
    "box_spiral",
    "right_tee",
    "center_ptr",
    "rightbutton",
    "circle",
    "rtl_logo",
    "clock",
    "sailboat",
    "coffee_mug",
    "sb_down_arrow",
    "cross",
    "sb_h_double_arrow",
    "cross_reverse",
    "sb_left_arrow",
    "crosshair",
    "sb_right_arrow",
    "diamond_cross",
    "sb_up_arrow",
    "dot",
    "sb_v_double_arrow",
    "dotbox",
    "shuttle",
    "double_arrow",
    "sizing",
    "draft_large",
    "spider",
    "draft_small",
    "spraycan",
    "draped_box",
    "star",
    "exchange",
    "target",
    "fleur",
    "tcross",
    "gobbler",
    "top_left_arrow",
    "gumby",
    "top_left_corner",
    "hand1",
    "top_right_corner",
    "hand2",
    "top_side",
    "heart",
    "top_tee",
    "icon",
    "trek",
    "iron_cross",
    "ul_angle",
    "left_ptr",
    "umbrella",
    "left_side",
    "ur_angle",
    "left_tee",
    "watch",
    "leftbutton",
    "xterm",
    "ll_angle",
    "X_cursor",
    "lr_angle",
    "none",
    "None",
    None,
)
USE_IMG_LIST = (
    "AVIF",
    "BLP",
    "BMP",
    "DDS",
    "DIB",
    "EPS",
    "GIF",
    "ICNS",
    "ICO",
    "IM",
    "JPEG",
    "JPEG 2000",
    "MPO",
    "MSP",
    "PCX",
    "PNG",
    "PPM",
    "QOI",
    "SGI",
    "SPIDER",
    "TGA",
    "TIFF",
    "WebP",
    "XBM",
)
ANCHOR_LIST = ("w", "n", "s", "e", "nw", "ne", "se", "sw", "center")
LABELANCHOR_LIST = ("nw", "n", "ne", "en", "e", "es", "se", "s", "sw", "ws", "w", "wn")
RELIEF_LIST = ("solid", "flat", "raised", "sunken", "ridge", "groove")
PLACE_LIST = ("left", "right", "center")
ORIENTATION_LIST = ("vertical", "horizontal")
# graph
BIN_HIST_LIST = ("auto", "fd", "doane", "scott", "stone", "rice", "sturges", "sqrt")
# nparray
METHOD_LIST = (
    "inverted_cdf",
    "averaged_inverted_cdf",
    "closest_observation",
    "interpolated_inverted_cdf",
    "hazen",
    "weibull",
    "linear",
    "median_unbiased",
    "normal_unbiased",
)
DATE_WORD = (
    "NAT",
    b"NAT",
    "NaT",
    b"NaT",
    "nat",
    b"nat",
    "NOW",
    b"NOW",
    "now",
    b"now",
    "TODAY",
    b"TODAY",
    "today",
    b"today",
)
CASTING_LIST = ("no", "equiv", "safe", "same_kind", "unsafe")
GRAPH_COLOR = (
    "#4477aa",
    "#ee7733",
    "#111211",
    "#aa66cc",
    "#77aadd",
    "#ffa94d",
    "#55aa55",
    "#cc3311",
    "#cc99ff",
    "#ff8888",
    "#444444",
    "#888888",
    "#332288",
    "#88ccee",
    "#44aa99",
    "#117733",
    "#999933",
    "#ddcc77",
    "#cc6677",
    "#882255",
    "#aa4499",
    "#dddddd",
)
LABELPLACELIST = (
    "upper right",
    "upper left",
    "lower left",
    "lower right",
    "right",
    "center left",
    "center right",
    "lower center",
    "upper center",
    "center",
    "best",
)
