__all__ = ["_SET_OBJ"]

class _SET_OBJ:
    def _nums(self, val, other=None): ...
    def _num0s(self, val, mins=0): ...
    def _num0(self, val, mins=0): ...
    def _bols(self, j, o=True): ...
    def _to_str(self, s): ...
    def _is_str(self, s): ...
    def _to_number(self, val): ...
    def _is_number(self, val): ...
    def _is_real(self, val): ...
    def _to_real(self, val): ...
    def _is_int(self, val): ...
    def _is_float(self, val): ...
    def _up0s(self, val, min): ...
    def _to_str_flat_list(self, array): ...
    def _to_flat_list(self, array): ...
    def _flatten(self, lst): ...
    def _listchose(self, val, arr, other=None): ...
    def _fpixels(self, val): ...
    def _dwh(self, val, other=None): ...
    def _dwh_int(self, val, other=None): ...
    @property
    def __firstlineno__(self) -> int: ...
    @property
    def __static_attributes__(self) -> list[str]: ...
    @property
    def __name__(self) -> str: ...
    @property
    def __module__(self) -> str: ...
    @property
    def __base__(self) -> type | None: ...
    @property
    def __bases__(self) -> tuple[type, ...]: ...
    @property
    def __mro__(self) -> tuple[type, ...]: ...
    @property
    def __dictoffset__(self) -> int: ...
    @property
    def __flags__(self) -> int: ...
    @property
    def __itemsize__(self) -> int: ...
